
#define REQUEST_QUEUE (WM_USER + 1)
#define REQUEST_EXECUTE (WM_USER + 2)
#define REQUEST_COMPLETE (WM_USER + 3)
#define REQUEST_EXECUTE_COMPLETE (WM_USER + 4)
#define REQUEST_IDLESENSE (WM_USER + 5)

#define IDLESENSE_ON		1
#define IDLESENSE_OFF		2